const C = {
    RECEIVING_DATA: 'RECEIVING_DATA',
    SELECT_MESSAGE: 'SELECT_MESSAGE',
    DESELECT_MESSAGE: 'DESELECT_MESSAGE',
    CHANGE_FILTER: 'CHANGE_FILTER',
    CHANGE_ORDER: 'CHANGE_ORDER'
};

export default C;